<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.voxelhorizons</groupId>
    <artifactId>VoxelCore</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>VoxelCore</name>

    <modules>
        <module>voxelcore-common</module>
        <module>voxelcore-plugin</module>
        <module>voxelcore-v1_12</module>
        <module>voxelcore-v1_14</module>
        <module>voxelcore-v1_19_4</module>
        <module>voxelcore-v1_20_5</module>
        <module>voxelcore-v1_21_4</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>8</maven.compiler.release>
        <spigot.v1_12>1.12.2-R0.1-SNAPSHOT</spigot.v1_12>
        <spigot.v1_14>1.14.4-R0.1-SNAPSHOT</spigot.v1_14>
        <spigot.v1_19_4>1.19.4-R0.1-SNAPSHOT</spigot.v1_19_4>
        <spigot.v1_20_5>1.20.5-R0.1-SNAPSHOT</spigot.v1_20_5>
        <spigot.v1_21_4>1.21.4-R0.1-SNAPSHOT</spigot.v1_21_4>
    </properties>

    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/groups/public/</url>
        </repository>
    </repositories>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.6.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
